### ISSUE TITLE
CMake error when bulid commandcenter

### ISSUE THREAD

**Issue by Timkeeper2018** [cpp-sc2/cpp-sc2#105]
Hey, sorry to bother you. 
When I use your commandcenter and build it,  I ran into a problem when I used your commandcenter and built it. I got an error while using cmake.

“-- Including ipv6_config.h from F:/commandcenter/build/cpp-sc2/contrib/ipv6-parse
CMake Error at cpp-sc2/src/CMakeLists.txt:107 (set_target_properties):
  set_target_properties Can not find target to add properties to: sc2renderer”

Do you have any idea about this ? Thanks a lot.

**Comment by Timkeeper2018** [comment]
by the way, I use windows as the development environment

**Comment by alkurbatov** [comment]
Hi @Timkeeper2018

Fixed in https://github.com/cpp-sc2/cpp-sc2/commit/a319382048bf29fa31d03f41ff2d51ed0218214e but I forgot to update the API submodule in CommandCenter. :(

Fixed in https://github.com/cpp-sc2/commandcenter/commit/90a1c11678628025fda74b817a0bbe6b580f2f73, please update the submodule and retry.

**Comment by alkurbatov** [comment]
@Timkeeper2018 have you had a chance to test the build?

**Comment by alkurbatov** [comment]
Added couple of other fixes and CI. Now CommandCenter can be built under all platforms.
@Timkeeper2018 please let me know if build still doesn't work for you.

**Comment by Timkeeper2018** [comment]
yes, it works, sorry, i forget to close it,thanks a lot
