### ISSUE TITLE
Add isCarringVespene and isCarringMinerals unit filters

### ISSUE THREAD

**Issue by alkurbatov** [cpp-sc2/cpp-sc2#82]

**Comment by ImpulseCloud** [comment]
@alkurbatov These have been available since the initial commit in sc2_client.h 
Line 141: IsCarryingMinerals , Line 148: IsCarryingVespene

They check for the specific mineral/vespene buffs. (but may not include HighYieldVespene, which is new, I believe?)

**Comment by alkurbatov** [comment]
It is available, but it is not filter, just a method of sc2::Unit. The idea is to provide a filter without necessity to write something (even lamda is not really needed here).

**Comment by alkurbatov** [comment]
Oh, well, yes, we can reuse these functions, although it is weird that we have separate filter function in sc2_client.h.

**Comment by ImpulseCloud** [comment]
Yeah, I assume it was put in sc2_client.h to make it more visible to people to make it obvious how to check an individual unit is carrying resources? Because otherwise, it may be easy to mistakenly use 'vespene/mineral_contents' of Unit.

The implementation is the easiest way to accomplish it. It only shows up in the buffs. The 'vespene_contents' and 'mineral_contents' are only for geysers and mineral-patches.

I tested the following and it works well. I think this feature can be closed.
```
    auto miners = gAPI->observer().GetUnits(sc2::IsCarryingMinerals);
    auto vespeners = gAPI->observer().GetUnits(sc2::IsCarryingVespene);
```

Though the current implementation doesn't check if it's a worker_type (or MULE) first, so maybe a little speedup there. *shrug* Ideally, you'd have a separate list of workers and only call it on them.

**Comment by alkurbatov** [comment]
I am mostly curious why the filters were scattered across different files. But, yeah, looks like it is enough to move these functions info sc2_unit_filters and close this issue.

**Comment by alkurbatov** [comment]
Refactored and closed.
